# Generated by Django 2.1.5 on 2019-01-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_dsc_pertence_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='dsc_pertence_funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario'),
            preserve_default=False,
        ),
    ]
