# Generated by Django 2.1.5 on 2019-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_empresa', models.CharField(help_text='Nome da Empresa', max_length=100)),
            ],
        ),
    ]
